server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registry
    username: registry
    password: registry
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas:
      - public
      - registry
    locations:
      classpath:db/migration
    baseline-on-migrate: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    sql: info
